# vim: ft=yaml
service: mini-irawo
image: tobisanh/mini-irawo
servers:
  - 95.217.219.44
ssh:
  keys_only: true
  keys: [ "deploy.key" ]
proxy:
  ssl: true
  host: mini-irawo.tobihans.space
registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
volumes:
  - "app_storage:/app/storage"
